---
# Test cause of Procfilemissing

name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prod-deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    environment: testing
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
      - name: Set subdomain (ensure is lowercase for dokku)
        run: |
          set -x
          echo SUBDOMAIN=`echo main` >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Create dokku app for pr branch if dosent already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app ${{ env.SUBDOMAIN }}
          ssh dokku@$DOKKU_HOST -C "apps:create ${{ env.SUBDOMAIN }}" | true

      - name: Push to dokku
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
          git remote add dokku dokku@$DOKKU_HOST:${{ env.SUBDOMAIN }}
          git push -f dokku ${{ env.SUBDOMAIN }}

          echo Visit your app here: http://${{ env.SUBDOMAIN }}.${{ secrets.DOKKU_HOST }}.sslip.io:80
